name: Mike Lyons Photo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42872
title: Fashion and Advertising
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73827506-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#625d63'
    - '#e8e1db'
    - '#0a0809'
    - '#b49a81'
    - '#3a7db1'
  brandStrength: 0.9375
  lightness: 0.9493599771521986
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
